export const techs: Record<string, string> = {
  tailwind: "Tailwind CSS",
  "next.js": "Next.js",
  supabase: "Supabase",
  "react.js": "React.js",
  typescript: "TypeScript",
  openweather: "OpenWeather API",
  redux: "Redux",
  zustand: "Zustand",
  javascript: "JavaScript",
  sass: "SASS",
  vite: "Vite",
  "node.js": "Node.js",
  "express.js": "Express.js",
  mongodb: "MongoDB",
  postgresql: "PostgreSQL",
  html: "HTML",
  css: "CSS",
}
